name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: docker build -t nicom27/conversor:${{ github.sha }} .

      - name: Push image (commit tag)
        run: docker push nicom27/conversor:${{ github.sha }}

      - name: Tag as latest  # cada vez que se genere una nueva imagen le cambia el nombre
        run: |
          docker tag nicom27/conversor:${{ github.sha }} nicom27/conversor:latest
          docker push nicom27/conversor:latest

