name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 #clona repo a la vm para asi acceder

      - name: Login to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4 #instala python 3.12
        with:
          python-version: 3.12

      - name: Install dependencies #instala las dependencias que estan en requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Build Docker image #construye la imagen docker usando el dockerfile
        run: docker build -t nicom27/conversor:tagname .

      - name: Docker push
        run: docker push nicom27/conversor:tagname
